### ISSUE TITLE
Problem Applying Changes to Script.pck in 'Ren Dystopia'

### ISSUE THREAD

**Issue by ProMisu** [thesupersonic16/DALTools#33] opened 2024-09-07 20:17 UTC
I am having an issue with ScriptDialogueEditor while working on 'Ren Dystopia', which was recently released on Steam. I can open the Script.pck file and view all the dialogues. However, when I try to apply the changes back to the Script.pck file, the game gets stuck on 'Now Loading'. Additionally, sometimes in the 'Name' field, I see '0xFF' instead of 'None', unlike in 'Rio Reincarnation'.
I'm not sure if I did something wrong during the compiling process.

**Comment by Choviics** [comment] 2024-09-07 22:30
> I am having an issue with ScriptDialogueEditor while working on 'Ren Dystopia', which was recently released on Steam. I can open the Script.pck file and view all the dialogues. However, when I try to apply the changes back to the Script.pck file, the game gets stuck on 'Now Loading'. Additionally, sometimes in the 'Name' field, I see '0xFF' instead of 'None', unlike in 'Rio Reincarnation'.
> 
> I'm not sure if I did something wrong during the compiling process.

I have de same problem 😔

**Comment by thesupersonic16** [comment] 2024-09-08 03:33
Issues should now be fixed by 3d75566515821b7748672e75db89f8da35d55bfe, you should beable to pull the changes, or if you are not compiling you can grab a build from [GitHub Actions](https://nightly.link/thesupersonic16/DALTools/workflows/build/master/DALTools-Release.zip). please let me know if the issue is resolved or not.


![DateALive_RD_qOugl0DZ33](https://github.com/user-attachments/assets/ceee9a57-4d76-4512-b41d-2e2a9003a3b9)

**Comment by Choviics** [comment] 2024-09-08 15:28
> Issues should now be fixed by [3d75566](https://github.com/thesupersonic16/DALTools/commit/3d75566515821b7748672e75db89f8da35d55bfe), you should beable to pull the changes, or if you are not compiling you can grab a build from [GitHub Actions](https://nightly.link/thesupersonic16/DALTools/workflows/build/master/DALTools-Release.zip). please let me know if the issue is resolved or not.
> 
> ![DateALive_RD_qOugl0DZ33](https://private-user-images.githubusercontent.com/25761885/365412285-ceee9a57-4d76-4512-b41d-2e2a9003a3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDkzNDgsIm5iZiI6MTcyNTgwOTA0OCwicGF0aCI6Ii8yNTc2MTg4NS8zNjU0MTIyODUtY2VlZTlhNTctNGQ3Ni00NTEyLWI0MWQtMmUyYTkwMDNhM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE1MjQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOGIyNWYwYTNhZGY5YTNiNjBhZDBmNTAxYzJiNTdlNzI2NmY0MTUzYjA4YjNhZDIyNDIxOTA2MGE0NjgwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.thmx5ZyytjHlVv1XSZbAt8fE-s93Fjwu2Ir5aXAsLd0)

Works fine! thx for fixing

**Comment by Choviics** [comment] 2024-09-08 15:36
> Issues should now be fixed by [3d75566](https://github.com/thesupersonic16/DALTools/commit/3d75566515821b7748672e75db89f8da35d55bfe), you should beable to pull the changes, or if you are not compiling you can grab a build from [GitHub Actions](https://nightly.link/thesupersonic16/DALTools/workflows/build/master/DALTools-Release.zip). please let me know if the issue is resolved or not.
> 
> ![DateALive_RD_qOugl0DZ33](https://private-user-images.githubusercontent.com/25761885/365412285-ceee9a57-4d76-4512-b41d-2e2a9003a3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDkzNDgsIm5iZiI6MTcyNTgwOTA0OCwicGF0aCI6Ii8yNTc2MTg4NS8zNjU0MTIyODUtY2VlZTlhNTctNGQ3Ni00NTEyLWI0MWQtMmUyYTkwMDNhM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE1MjQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOGIyNWYwYTNhZGY5YTNiNjBhZDBmNTAxYzJiNTdlNzI2NmY0MTUzYjA4YjNhZDIyNDIxOTA2MGE0NjgwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.thmx5ZyytjHlVv1XSZbAt8fE-s93Fjwu2Ir5aXAsLd0)

something that happens is that when exporting all the dialogs, the application crashes but ends up exporting the files anyway

**Comment by Choviics** [comment] 2024-09-08 15:58
> Issues should now be fixed by [3d75566](https://github.com/thesupersonic16/DALTools/commit/3d75566515821b7748672e75db89f8da35d55bfe), you should beable to pull the changes, or if you are not compiling you can grab a build from [GitHub Actions](https://nightly.link/thesupersonic16/DALTools/workflows/build/master/DALTools-Release.zip). please let me know if the issue is resolved or not.
> 
> ![DateALive_RD_qOugl0DZ33](https://private-user-images.githubusercontent.com/25761885/365412285-ceee9a57-4d76-4512-b41d-2e2a9003a3b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDkzNDgsIm5iZiI6MTcyNTgwOTA0OCwicGF0aCI6Ii8yNTc2MTg4NS8zNjU0MTIyODUtY2VlZTlhNTctNGQ3Ni00NTEyLWI0MWQtMmUyYTkwMDNhM2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDE1MjQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOGIyNWYwYTNhZGY5YTNiNjBhZDBmNTAxYzJiNTdlNzI2NmY0MTUzYjA4YjNhZDIyNDIxOTA2MGE0NjgwNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.thmx5ZyytjHlVv1XSZbAt8fE-s93Fjwu2Ir5aXAsLd0)

and I don't know if it is me opening the files wrong but some dialogs either in tsv or csv are badly separated.

**Comment by thesupersonic16** [comment] 2024-09-08 16:43
Not sure why I have allowed new lines in CSVs, might be safer to escape them.

**Comment by thesupersonic16** [comment] 2024-09-08 17:15
Pushed some changes which should show any errors on script loading. Import and exports should now only take escaped line endings. You can get the new build by using the same link from before or pull the repo and build.

**Comment by Choviics** [comment] 2024-09-08 17:37
> Pushed some changes which should show any errors on script loading. Import and exports should now only take escaped line endings. You can get the new build by using the same link from before or pull the repo and build.

Thank you so much! It works perfectly now, I really appreciate it!

**Comment by Choviics** [comment] 2024-09-08 18:49
> Pushed some changes which should show any errors on script loading. Import and exports should now only take escaped line endings. You can get the new build by using the same link from before or pull the repo and build.

Can I ask you one last question, is this problem already due to a game configuration, are the “ñ” “¿” and the accents used in Spanish, is there a way to fix this?

![image](https://github.com/user-attachments/assets/9194a0f0-abd4-4ed1-ac3f-caf993b59787)

**Comment by Choviics** [comment] 2024-09-08 19:06
Sorry, I didn't realize, it's with the font editor that I need to create these letters.

**Comment by Choviics** [comment] 2024-09-08 23:46
> Pushed some changes which should show any errors on script loading. Import and exports should now only take escaped line endings. You can get the new build by using the same link from before or pull the repo and build.

I'm not sure if it's a problem or if I did something wrong, but when I save the fonts with the textures I made, they don't apply to the game

![image](https://github.com/user-attachments/assets/7b8520cf-a106-4356-b3d1-0a1ba50e11e0)

**Comment by thesupersonic16** [comment] 2024-09-09 01:55
I have not checked fonts for Ren Dystopia. Rio Reincarnation did sometimes not like adding new characters. Try editing both Font1 and FontMsg1 files. Worst case you may have to do character substitution by creating a `replace.ini` file (also untested).

**Comment by thesupersonic16** [comment] 2024-09-09 01:58
Can you send me your Font pck files? I might check it later.

**Comment by Choviics** [comment] 2024-09-09 02:03
> Can you send me your Font pck files? I might check it later.

of course, here are my fonts that I made

[FONTS.zip](https://github.com/user-attachments/files/16924537/FONTS.zip)

**Comment by thesupersonic16** [comment] 2024-09-09 08:20
The game might be excluding the characters, I don't remember how I fixed it for Russian.
You can try character substitution, for example using the full-width characters.

Just put it next to the Script.pck. And change your characters to match whats in the ini. You don't need the ini for playing, only for editing.
[replace.zip](https://github.com/user-attachments/files/16927473/replace.zip)

I believe the editor will convert the characters on import aswell. Not sure if this method had been tested.

As I was about to finish writing this message I went to try the full-width, and it appears to not play well. Might need to mess around more later.
![image](https://github.com/user-attachments/assets/8af29bf5-01fd-4f08-81a3-6543847af39e)

**Closed** 2024-09-12 19:07 UTC
